### ISSUE TITLE
Future Linux Support ? Which kind of cameras are supported?

### ISSUE THREAD

**Issue by mambro** [hezhao/Calibrator#3]
Hi,
first great job with your Projector-Camera Calibrator Tool.

1) I have seen in the readme of this project you  have built successfully your work under Windows and OS X. What about Linux support ?  

2) I don't understand from your main readme if your work is targeted to Canon  cameras or if it usable with other kind of cameras. Can you tell me something more about this second topic?

Thanks, 

Michele Mambrini

**Comment by hezhao** [comment]
Canon EDSDK is Windows and Mac only, so as Nikon SDK. Currently the software only support Canon EDSDK. It's possible to add Nikon, but Nikon SDK is difficult to work with.

If there is a camera that has Linux SDK, there should be no problem to port the entire project to Linux.

**Comment by mambro** [comment]
Thank you very much for your answer, now I fully understand the aim and possibilities offered by your work.
