### ISSUE TITLE
Camera Preview Using iSight Camera Not Canon EOS 40D

### ISSUE THREAD

**Issue by colinzballz** [hezhao/Calibrator#5]
Hi,

I have installed release v0.2 of Calibrator on a MacBook Pro i5 running El Capitan 10.11.3 and also an i7 MacBook Pro i7 running Sierra 10.12.3 

The camera is using EOS Utility 2.14.31.0

On the capture page of Calibrator, the EOS 40D drop down entry links to the built in iSight camera and the entry for the iSight shows no image stream - I suspect that is actually the EOS preview not starting correctly. 

Please can you help me to resolve this issue?

I have attached some screenshots and a Console log - let me know if you need any further info...

Thanks

Colin

![isight](https://cloud.githubusercontent.com/assets/4474264/23103276/bcf9fd02-f6b0-11e6-8081-6028a20da9a1.png)
![eos](https://cloud.githubusercontent.com/assets/4474264/23103277/bd1a84f0-f6b0-11e6-8fd7-572cfd66473f.png)

[Console - Calibrator Messages.txt](https://github.com/hezhao/Calibrator/files/785919/Console.-.Calibrator.Messages.txt)

**Comment by colinzballz** [comment]
[EOS Utility 2_2017-02-19-124125_wks51155.wakeups_resou.txt](https://github.com/hezhao/Calibrator/files/785927/EOS.Utility.2_2017-02-19-124125_wks51155.wakeups_resou.txt)
[Calibrator_2017-02-19-124300_wks51155.wakeups_resource.txt](https://github.com/hezhao/Calibrator/files/785928/Calibrator_2017-02-19-124300_wks51155.wakeups_resource.txt)

I've included some additional diagnostic logs

**Comment by hezhao** [comment]
The preview image is wrong, but when you select 40D, the captured image should be coming from 40D

**Comment by colinzballz** [comment]
I shall do some further tests and see if images fro the camera are captured

**Comment by colinzballz** [comment]
It just worked :) :)

The problem was caused by an earlier test of MadMapper which crashed

Thanks for your help
